version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
